config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins

  resources :categories
  resources :movies do
    post 'disable', on: :member
    post 'active', on: :member
  end
  root to: 'home#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true
  has_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :category
  validates :title, :description, :rent_price, presence: true

  enum status: { active: 0, disabled: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_admin!, only: %i[new create edit update destroy]
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @categories = Category.all
  end

  def show; end

  def edit; end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def update
    if @category.update(category_params)
      redirect_to @category
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path, notice: 'Category was successfully destroyed.'
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:title)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_admin!, only: %i[new create edit update destroy]
  before_action :set_movie, only: %i[show edit update destroy]

  def index
    @movies = Movie.all
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to @movie, notice: 'Movie was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def show; end

  def update
    if @movie.update(movie_params)
      redirect_to @movie
    else
      render :edit
    end
  end

  def destroy
    @movie.destroy
    redirect_to movies_path, notice: 'Movie was successfully destroyed.'
  end

  def disable
    @movie = Movie.find(params[:id])
    @movie.disabled!
    redirect_to @movie, notice: 'Filme desabilitado.'
  end

  def active
    @movie = Movie.find(params[:id])
    @movie.active!
    redirect_to @movie, notice: 'Filme disponível.'
  end

  private

  def set_movie
    @movie = Movie.find(params[:id])
  end

  def movie_params
    params.require(:movie).permit(:title, :description, :rent_price, :category_id)
  end
end

app/views/categories/_form.html.erb
 <% if @category.errors.any? %>
  <h4>We were unable to save we found some errors:</h4>
  <ul>
    <% @category.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @category, local: true do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.submit 'Save Category' %> 
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>

<%= render 'form', category: @category %>

app/views/categories/index.html.erb
<h1>Categorias</h1>

<table class='table'>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.title, category %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/categories/new.html.erb
<h1>Categories#new</h1>

<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<h1>#Show Category</h1>
<%= flash[:notice] %>

<%= link_to 'Voltar', movies_path %>
<br><br>

<dl>
  <dt>Title</dt>
  <dd><%= @category.title %></dd>
</dl>

<% if admin_signed_in? %>
  <%= link_to 'Edit', edit_category_path(@category), class: 'btn btn-primary' %> |
  <%= link_to 'Delete', category_path(@category), method: :delete, class: 'btn btn-primary' %> 
<% end %>
<br><br><br>

<strong><p>Filmes</p></strong>
<% @category.movies.each do |movie| %>
  <p><%= link_to movie.title, movie %></p>
<% end %>

app/views/home/index.html.erb
<h1>Início</h1>
<% name = current_user.present? ? current_user.email : 'Visitante! Faça seu cadastro e alugue um filme.' %>
<h2>Bem vindo, <%= name %> </h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <main class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>

app/views/movies/_form.html.erb
 <% if @movie.errors.any? %>
  <h4>We were unable to save we found some errors:</h4>
  <ul>
    <% @movie.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @movie, local: true do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area(:description, cols: 15, rows: 5)%>
  </div>
  <div>
    <%= f.label :rent_price %>
    <%= f.text_field :rent_price %>
  </div>
  <div>
    <%= f.label :category_id %>
    <%= f.text_field :category_id %>
  </div>
  <div>
    <%= f.submit 'Save Movie' %> 
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Movies#edit</h1>

<%= render 'form', movie: @movie %>

app/views/movies/index.html.erb
<h1>Lista de Filmes</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Title</th>
      <th>Categories</th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= link_to movie.title, movie %></td>
        <td><%= link_to movie.category.title, category_path(movie.category_id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/movies/new.html.erb
<h1>Movies#new</h1>

<%= render 'form', movie: @movie %>

app/views/movies/show.html.erb
<h1>Categoria(<%= @movie.category.title %>) / Filme(<%= @movie.title %>)</h1>
<% if @movie.active? %>
  <dl>
    <dt>Title:</dt>
    <dd><%= @movie.title %></dd>
    <dt>Description:</dt>
    <dd><%= @movie.description %></dd>
    <dt>Rent price:</dt>
    <dd><%= @movie.rent_price %></dd>
  </dl>
<% else %>
 <p>Filme temporariamente indisponível.</p>
<% end %>

<% if admin_signed_in? %>
  <% if @movie.active? %>
    <%= button_to 'Desabilitar', disable_movie_path(@movie), data: { disable_with: 'Estamos desabilitando....' } %>
  <% else %>
    <%= button_to 'Reativar', active_movie_path(@movie), data: { disable_with: 'Estamos reativando....' } %>
  <% end %>
<% end %>

<br>

<% if admin_signed_in? %>
  <%= link_to 'Edit', edit_movie_path(@movie), class: 'btn btn-primary' %> |
  <%= link_to 'Delete', movie_path(@movie), method: :delete, class: 'btn btn-primary' %> 
<% end %>
<br><br>

<%= link_to 'Voltar', movies_path %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md fixed-top navbar-dark bg-primary">
  <%= link_to 'Movie-Storie', root_path, class: "navbar-brand" %>
  <button class="navbar-toggler p-0 border-0" type="button" data-toggle="offcanvas">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div  class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to 'Início', root_path, class: 'nav-link btn btn-primary' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Categorias', categories_path, class: 'nav-link btn btn-primary' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Filmes', movies_path, class: 'nav-link btn btn-primary' %>
      </li>
      <% if admin_signed_in? %>
        <li class="nav-item">
          <%= link_to current_admin.email, edit_admin_registration_path,class: 'nav-link btn btn-primary' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sair', destroy_admin_session_path, method: :delete, class: 'nav-link btn btn-primary' %>
        </li>
      <% elsif user_signed_in? %>
        <li class="nav-item">
          <%= link_to current_user.email, edit_user_registration_path,class: 'nav-link btn btn-primary' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sair', destroy_user_session_path, method: :delete, class: 'nav-link btn btn-primary' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Entrar', new_user_session_path, class: 'nav-link btn btn-primary' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Cadastrar', new_user_registration_path, class: 'nav-link btn btn-primary' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>